secret:
    databaseUrl: ENC[AES256_GCM,data:c5Huhy7ktn0p+CioNqAc7tDOGe6PWhEWrh7FyigMnZMKREii28YJ7qaQQ8MaJo0Z3Ypp/iRi0stUtDdqUIbRawedZrgIl25t4Xvm+p8AlN2TbKBJEmvM2DZ7kJmilWIVgg==,iv:HdQ3GFEOxZ0LZ596lqVK9aKwiWEedA4wXSFJOGfuluE=,tag:v68pXmmaEDeSRueYE2KS2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cletq4h7lntlu2eclkf37pe4uk68lngu40kp43mnqql8d4xh9vhqdrrdjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRTZTcXliSHJFcm5ZRWlL
            aWtJNWlQTGRjalNKQmVBZXVJajRLUEhieUFjCm45Qk5wMWZEOXV1WTNzRk41WW82
            WW50TGhHSVhPdjlmcWFMU2lNKzRqbmMKLS0tIFc4RC9LdWZVQ3dYNWVNbjhNa05s
            ZG9nQi9FOTIzYkZ0TUp3RHRiMlVlRUkKaVdv1is/Cz0jmc+sH04p2z38Y28PCsHv
            ttN8jfLTLmzi3YtHbg3I11ht5dTaRbqvgr+T9eIsclKXtYagl3ZsSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T13:21:15Z"
    mac: ENC[AES256_GCM,data:/YEgp8bGGa9mqSLpfREZ8xZed4GCeYxYWjNmdC5H2/ZpRcfgALxcrkXKT40KkLAHaGqSfAajSqC6cgMPrjYzAy6yGBP8cGYAfxTQ0zSfViZjCIVFN8QvM9Dt5PMPeMrIUvtmrk4Jf3JLqH7c+93qzVuLHUkxuappnP6B0QUDtv8=,iv:e/CmGWpCqhFJcRpYcWnsFgHbUWWRRkMv33dgnQQHnmk=,tag:e5J6Zr2N3Gev6MSNoruIpA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
