secret:
    databaseUrl: ENC[AES256_GCM,data:Pz66rxibyIoBB9JmIDtBuoj5HfUiYQayC+yqmQ6Ysya60WZ7ZoaUB1MWSH30RZzEEXJataJByomwFejAOh8QN+ZAVuJ6MQvrrmqkaUa6BnS13Y1Up2tpXLG2HkU3W83kvCllf6wjMt8=,iv:9QmL7kGeMY43srs2ZyM2He5A55aSUMBSBxaCC+6h/Nw=,tag:iDWy1p+01Kw2uy+Nk/CWQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cletq4h7lntlu2eclkf37pe4uk68lngu40kp43mnqql8d4xh9vhqdrrdjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRTZTcXliSHJFcm5ZRWlL
            aWtJNWlQTGRjalNKQmVBZXVJajRLUEhieUFjCm45Qk5wMWZEOXV1WTNzRk41WW82
            WW50TGhHSVhPdjlmcWFMU2lNKzRqbmMKLS0tIFc4RC9LdWZVQ3dYNWVNbjhNa05s
            ZG9nQi9FOTIzYkZ0TUp3RHRiMlVlRUkKaVdv1is/Cz0jmc+sH04p2z38Y28PCsHv
            ttN8jfLTLmzi3YtHbg3I11ht5dTaRbqvgr+T9eIsclKXtYagl3ZsSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T09:40:49Z"
    mac: ENC[AES256_GCM,data:af65fXkPxycpmQMsZzFXYlmgxQHiWhZMGHHEg2JDwdCQQBPUvED9D5JK/PPo3kt/mLm4SZFnMWeGed3PBCroBhfxsHTlPLOoaJuCevIde+q0rFwOMuXvdF83YFNTuInoviO4Oz/jrHcJBlss7QXlpQsdw6wga4PM8o6T/aNnzNs=,iv:G0HUJacf58f3MwG5eATrA71a1TFsHqISidXajYvgZWk=,tag:gtxyL7H0nI0Usg3/Wt/Pnw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
