apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: default
spec:
  limits:
    - type: Container
      default:          # применяется если limits не указан
        cpu: "500m"
        memory: "256Mi"
      defaultRequest:   # применяется если requests не указан
        cpu: "100m"
        memory: "128Mi"
      max:              # Pod не может запросить больше
        cpu: "2"
        memory: "500Mi"
