secret:
    dbName: ENC[AES256_GCM,data:AkabBvE=,iv:EaDhwDlLrQ/hrO4y9NLDxKm1slZHM4eXuocaYsd41z0=,tag:rpGGI4vco02h+9UyBV0t7Q==,type:str]
    dbUser: ENC[AES256_GCM,data:Ehz0Wgzr8Jw3ng==,iv:cdzxwXgYD+nPL7WmzjrnEWdpsxcIegy+n1SHgMLjBs8=,tag:Tt1yeO7iClYsvpC+8eHe6w==,type:str]
    dbPassword: ENC[AES256_GCM,data:iE9gRWbug2IjuL6eSW+gFA==,iv:Sz2A1LvmVBqTvEG5V5qXrqGQQZs+2OAY5pcrVwjmuA4=,tag:1XbXzOWwXmCD42P7dXcg1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cletq4h7lntlu2eclkf37pe4uk68lngu40kp43mnqql8d4xh9vhqdrrdjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCU2loUTFXaDdBTzJyTWdE
            VXlzMFBLNElFRFRFb1Z6dFkxT0lPYjZXeEg0CkdsL3JFbEt6cGwvR1hZN2RZNlFo
            U1g2Zm5JYVdCUk1jRlF1SlpsMDVpVUkKLS0tIHBlenlJVEcybi8wUWV1T2NLMHJJ
            TE9tMXJWcVlkdURJNi9lMmxnMXd3Ym8KMCExPRYAHLG5C6KUs+/pgloqzIBiyjgs
            o6ovdgZoPTU4eLZSF/HNh3liYsU9zn/zMsgQE1QnigffisXCGAaUyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T13:17:46Z"
    mac: ENC[AES256_GCM,data:oxk41eeUfwjrXbSIW0hpbme6ywRA0IjJd/+UbphWc73W1Kb+R3OXr3aowasQjA0IdU8aArOCNAhq1HHfTTQWW87Rt9fRjSkC57uoR38HHMMG3f29HpknKS1nVLb0gZ/h0Y9K+12KC3ZXvadTIn69OeRFQgj5y4hhq8Q+MeWrF4U=,iv:finUTNNZfaGl1StjflHYOvMLPjLROfox8bWsh3YxkKA=,tag:YRSK/JGGT5ZuloNDcmdbag==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
