apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: backend-api
          image: {{ .Values.image.name }}
          startupProbe:
            httpGet:
              path: /app/health
              port: {{ .Values.backend.port }}
            failureThreshold: 12
            timeoutSeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /app/health
              port: {{ .Values.backend.port }}
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /app/ready
              port: {{ .Values.backend.port }}
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
