name: Deploy k8s

on:
  push:
    branches: [main]

jobs:
  checks:
    uses: ./.github/workflows/pr-check.yml

  build:
    needs: [checks]
    runs-on: ubuntu-latest
    outputs:
      image_sha: ${{ steps.build-push.outputs.image_sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Вход в Docker Hub
        run: docker login -u ${{ vars.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Build and Push образа
        id: build-push
        env:
          IMAGE_SHA: ${{ vars.DOCKER_USER }}/backend:sha-${{ github.sha }}
          IMAGE_LATEST: ${{ vars.DOCKER_USER }}/backend:latest
        run: |
          docker build -t $IMAGE_SHA -t $IMAGE_LATEST .
          docker push $IMAGE_SHA
          docker push $IMAGE_LATEST
          echo "image_sha=$IMAGE_SHA" >> $GITHUB_OUTPUT

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config

      - name: Deploy to k3s
        run: |
          kubectl set image deployment/backend backend=${{ needs.build.outputs.image_sha }}
          kubectl rollout status deployment/backend --timeout=120s

  notify:
    name: Notify JOB
    needs: [checks, deploy, build]
    if: always()
    uses: ./.github/workflows/notify.yaml
    with:
      checks_result: ${{ needs.checks.result }}
      deploy_result: ${{ needs.deploy.result }}
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
