name: Deploy

on:
  push:
    branches: [main]

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  deploy:
    needs: checks
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/lesson/backend
            git pull origin main
            cd /var/www/lesson
            docker compose up --build -d backend
