name: Deploy

on:
  push:
    branches: [main]

jobs:
  # checks:
  #   uses: ./.github/workflows/pr-check.yml

  build:
    # needs: [checks]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}

       # 2. Подготовка Buildx для корректной сборки под AMD64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Сборка нового образа из свежего кода и push в Docker Hub
      - name: Build and push Backend image
        env: 
          IMAGE_SHA: ${{ secrets.DOCKERHUB_USER }}/backend:sha-${{ github.sha }}
          IMAGE_LATEST: ${{ secrets.DOCKERHUB_USER }}/backend:latest
        run: |
          docker build -t $IMAGE_SHA -t $IMAGE_LATEST .
            with:
              platforms: linux/amd64

          docker push $IMAGE_SHA
          docker push $IMAGE_LATEST



  deploy:
    needs: checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     

     

      # 4. Обновление на вашем VPS по SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd dev-less
            docker compose pull backend
            docker compose up -d backend

  notify:
    needs: [checks, deploy]
    uses: ./.github/workflows/notify.yml
