name: PR Checks

on:
  workflow_call:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 23, 24]
        include:
          - node-version: 24
            experimental: true

    continue-on-error: ${{ matrix.experimental == true }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Установка зависимостей
        run: npm ci

      - name: Линтинг
        run: npm run lint

      - name: Запуск тестов
        run: npm run test
