name: SAST / SCA scan

on:
  workflow_call:


jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.30.0/gitleaks_8.30.0_linux_x64.tar.gz \
            -o gitleaks.tar.gz
          tar -zxvf gitleaks.tar.gz
          chmod +x gitleaks

      - name: Run Gitleaks
        run: |
          ./gitleaks detect \
            --source=. \
            --config=.gitleaks.toml \
            --verbose \
            --redact \
            --exit-code 1

  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Run Semgrep scan
        run: |
          semgrep scan \
            --config=p/typescript \
            --config=p/nodejs \
            --config=p/owasp-top-ten \
            --config=p/jwt \
            --error \
            --exclude=node_modules \
            --exclude=dist \
            --exclude=build \
            --exclude=kubernetes \
            .
